# Generated by Django 2.2.3 on 2019-07-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projmanager', '0004_auto_20190716_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='task_id',
        ),
    ]
