# Generated by Django 2.2.3 on 2019-07-16 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projmanager', '0005_remove_information_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='task_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projmanager.Task'),
        ),
    ]
