# Generated by Django 2.2.3 on 2019-07-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projmanager', '0007_auto_20190716_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='task_id',
            new_name='id_task',
        ),
    ]
