# Generated by Django 2.2.3 on 2019-07-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projmanager', '0002_auto_20190716_1439'),
        ('projmanager', '0008_auto_20190716_1214'),
    ]

    operations = [
    ]
