# Generated by Django 2.2.3 on 2019-07-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projmanager', '0009_merge_20190717_1530'),
        ('projmanager', '0009_merge_20190717_1047'),
    ]

    operations = [
    ]
